import {
  User,
  School,
  DiagnosticCenter,
  Student,
  DiagnosisRequest,
  AuditLogEntry,
  Notification,
} from '@/types/database';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'م. أسامة الغامدي',
    email: 'osama@shakhesni.sa',
    phone: '0501234567',
    role: 'SYSTEM_ADMIN',
    roleArabic: 'مدير النظام',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
  },
  {
    id: 'usr-reception-1',
    name: 'سارة عبد الله الشمري',
    email: 'sara.reception@shakhesni.sa',
    phone: '0502345678',
    role: 'RECEPTIONIST',
    roleArabic: 'موظفة الاستقبال',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    centerId: 'center-1',
  },
  {
    id: 'usr-coord-1',
    name: 'د. فيصل بن خالد الدوسري',
    email: 'faisal.coord@shakhesni.sa',
    phone: '0503456789',
    role: 'CENTER_COORDINATOR',
    roleArabic: 'منسق مركز التشخيص',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    centerId: 'center-1',
  },
  {
    id: 'usr-specialist-1',
    name: 'د. منيرة آل سعود',
    email: 'monira.psych@shakhesni.sa',
    phone: '0504567890',
    role: 'DIAGNOSTIC_MEMBER',
    roleArabic: 'أخصائية نفسية قياس وتأهيل',
    specialization: 'التقييم النفسي والمعرفي',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    centerId: 'center-1',
  },
  {
    id: 'usr-specialist-2',
    name: 'أ. طارق المالكي',
    email: 'tariq.speech@shakhesni.sa',
    phone: '0505678901',
    role: 'DIAGNOSTIC_MEMBER',
    roleArabic: 'أخصائي نطق وتواصل',
    specialization: 'اضطرابات النطق واللغة والتواصل',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    centerId: 'center-1',
  },
  {
    id: 'usr-teamleader-1',
    name: 'د. عبد العزيز العتيبي',
    email: 'abdulaziz.tl@shakhesni.sa',
    phone: '0506789012',
    role: 'TEAM_LEADER',
    roleArabic: 'رئيس فريق التشخيص والتقييم',
    specialization: 'التربية الخاصة واضطرابات النمو',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    centerId: 'center-1',
  },
  {
    id: 'usr-supervisor-1',
    name: 'د. هدى التميمي',
    email: 'huda.supervisor@shakhesni.sa',
    phone: '0507890123',
    role: 'SUPERVISOR',
    roleArabic: 'مشرفة وباحثة مركز التشخيص',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150',
    centerId: 'center-1',
  },
  {
    id: 'usr-school-1',
    name: 'أ. أحمد القحطاني',
    email: 'ahmed.counselor@school.edu.sa',
    phone: '0508901234',
    role: 'SCHOOL_REP',
    roleArabic: 'موجه طلابي - مدرسة الأمل الابتدائية',
    schoolId: 'school-1',
  },
  {
    id: 'usr-parent-1',
    name: 'خالد بن محمد المطيري',
    email: 'khalid.parent@gmail.com',
    phone: '0509012345',
    role: 'PARENT',
    roleArabic: 'ولي أمر الطالب (فهد المطيري)',
  },
  {
    id: 'usr-parent-2',
    name: 'عبد الله السبيعي',
    email: 'subaie@gmail.com',
    phone: '0501112233',
    role: 'PARENT',
    roleArabic: 'ولي أمر الطالبة (ريما السبيعي)',
  },
  {
    id: 'usr-parent-3',
    name: 'يوسف الدوسري',
    email: 'dossary@gmail.com',
    phone: '0502223344',
    role: 'PARENT',
    roleArabic: 'ولي أمر الطالب (عمر الدوسري)',
  },
];

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'school-1',
    code: 'SCH-RIY-001',
    name: 'مدرسة الأمل النموذجية الابتدائية',
    city: 'الرياض',
    district: 'حي الصحافة',
    educationalStage: 'الابتدائية',
    principalName: 'أ. سعود الناصر',
    counselorName: 'أ. أحمد القحطاني',
    counselorPhone: '0508901234',
    activeRequestsCount: 4,
  },
  {
    id: 'school-2',
    code: 'SCH-RIY-002',
    name: 'مجمع المستقبل التعليمي',
    city: 'الرياض',
    district: 'حي الملقا',
    educationalStage: 'المتوسطة',
    principalName: 'د. خالد الزهراني',
    counselorName: 'أ. بدر المطيري',
    counselorPhone: '0501122334',
    activeRequestsCount: 2,
  },
];

export const INITIAL_CENTERS: DiagnosticCenter[] = [
  {
    id: 'center-1',
    code: 'CTR-RIY-CENTRAL',
    name: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
    city: 'الرياض',
    district: 'حي السليمانية',
    capacityPerDay: 15,
    activeTeamCount: 8,
    specializations: ['اضطراب طيف التوحد', 'صعوبات التعلم', 'الإعاقة الفكرية', 'اضطرابات النطق', 'فرط الحركة وتشتت الانتباه'],
    directorName: 'د. هدى التميمي',
    phone: '0114567890',
  },
  {
    id: 'center-2',
    code: 'CTR-JED-WEST',
    name: 'مركز التقييم الشامل لذوي الإعاقة - جدة',
    city: 'جدة',
    district: 'حي الشاطئ',
    capacityPerDay: 12,
    activeTeamCount: 6,
    specializations: ['اضطراب طيف التوحد', 'الإعاقات الحركية والبصرية', 'صعوبات التعلم'],
    directorName: 'د. وليد البقمي',
    phone: '0126543210',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    nationalId: '1092837465',
    fullName: 'فهد خالد محمد المطيري',
    gender: 'MALE',
    birthDate: '2018-04-12',
    ageYears: 8,
    grade: 'الصف الثاني الابتدائي',
    schoolId: 'school-1',
    schoolName: 'مدرسة الأمل النموذجية الابتدائية',
    parentId: 'usr-parent-1',
    parentName: 'خالد بن محمد المطيري',
    parentPhone: '0509012345',
    parentEmail: 'khalid.parent@gmail.com',
    medicalConditions: 'تأخر نمائي لغوي ملحوظ وصعوبة في التواصل الاجتماعي والتفاعل مع الأقران',
    notes: 'ملاحظ من قبل المعلم بعدم الاندماج ومواجهة نوبات تشتت عند تغير الروتين اليومي',
  },
  {
    id: 'std-2',
    nationalId: '1102938475',
    fullName: 'ريما عبد الله السبيعي',
    gender: 'FEMALE',
    birthDate: '2017-09-25',
    ageYears: 9,
    grade: 'الصف الثالث الابتدائي',
    schoolId: 'school-1',
    schoolName: 'مدرسة الأمل النموذجية الابتدائية',
    parentId: 'usr-parent-2',
    parentName: 'عبد الله السبيعي',
    parentPhone: '0501112233',
    parentEmail: 'subaie@gmail.com',
    medicalConditions: 'صعوبة بالغة في قراءة القوافي والأرقام والكتابة',
    notes: 'تحتاج لتقييم صعوبات تعلم محددة في القراءة والكتابة (Dyslexia)',
  },
  {
    id: 'std-3',
    nationalId: '1083746251',
    fullName: 'عمر بن يوسف الدوسري',
    gender: 'MALE',
    birthDate: '2019-02-10',
    ageYears: 7,
    grade: 'الصف الأول الابتدائي',
    schoolId: 'school-2',
    schoolName: 'مجمع المستقبل التعليمي',
    parentId: 'usr-parent-3',
    parentName: 'يوسف الدوسري',
    parentPhone: '0502223344',
    parentEmail: 'dossary@gmail.com',
    medicalConditions: 'فرط نشاط حركي شديد وتشتت انتباه مع اندفاعية عالية',
  },
];

export const INITIAL_REQUESTS: DiagnosisRequest[] = [
  {
    id: 'req-101',
    requestNumber: 'SHK-2026-0041',
    studentId: 'std-1',
    student: INITIAL_STUDENTS[0],
    schoolId: 'school-1',
    schoolName: 'مدرسة الأمل النموذجية الابتدائية',
    referredCenterId: 'center-1',
    referredCenterName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
    primaryCategory: 'AUTISM',
    primaryCategoryArabic: 'اشتباه اضطراب طيف التوحد',
    priority: 'HIGH',
    status: 'UNDER_EVALUATION',
    statusArabic: 'تحت التقييم والتشخيص',
    assignedTeamLeaderId: 'usr-teamleader-1',
    assignedTeamLeaderName: 'د. عبد العزيز العتيبي',
    assignedSpecialists: ['د. منيرة آل سعود (نفسي)', 'أ. طارق المالكي (نطق وتواصل)'],
    receptionistId: 'usr-reception-1',
    receptionistName: 'سارة عبد الله الشمري',
    createdAt: '2026-07-20T08:30:00Z',
    updatedAt: '2026-07-30T11:15:00Z',
    slaDaysTotal: 5,
    slaDaysRemaining: 2,
    isSlaPaused: false,
    slaBreached: false,
    qrCodeUrl: 'https://shakhesni.sa/verify/SHK-2026-0041',
    reportVerificationToken: 'VRF-8849-0041-SA',
    documents: [
      {
        id: 'doc-1',
        requestId: 'req-101',
        title: 'صورة هوية الطالب وولي الأمر',
        category: 'NATIONAL_ID',
        fileUrl: '/docs/national_id.pdf',
        fileName: 'identity_fahad.pdf',
        fileSize: '1.2 MB',
        uploadedBy: 'سارة عبد الله الشمري',
        uploadedAt: '2026-07-20T09:00:00Z',
        isVerified: true,
        aiAuditResult: {
          status: 'COMPLETE',
          summary: 'تم التحقق من مطابقة رقم الهوية والاسم مع السجل المدني للطلاب بنسبة 100%',
        },
      },
      {
        id: 'doc-2',
        requestId: 'req-101',
        title: 'التقرير الطبي الأولي لمركز الرعاية الصحية',
        category: 'MEDICAL_REPORT',
        fileUrl: '/docs/medical_report.pdf',
        fileName: 'pediatric_report.pdf',
        fileSize: '2.8 MB',
        uploadedBy: 'خالد بن محمد المطيري (ولي الأمر)',
        uploadedAt: '2026-07-20T09:30:00Z',
        isVerified: true,
        aiAuditResult: {
          status: 'COMPLETE',
          summary: 'يتضمن التقرير فحوصات السمع والنظر الأساسية وتاريخ التطور النمائي للطفل',
        },
      },
      {
        id: 'doc-3',
        requestId: 'req-101',
        title: 'ملاحظات المرشد الطلابي وتقييم المدرسة',
        category: 'SCHOOL_REPORT',
        fileUrl: '/docs/school_report.pdf',
        fileName: 'school_assessment.pdf',
        fileSize: '950 KB',
        uploadedBy: 'أ. أحمد القحطاني',
        uploadedAt: '2026-07-20T10:00:00Z',
        isVerified: true,
      },
    ],
    statusHistory: [
      {
        id: 'h-1',
        requestId: 'req-101',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        actorId: 'usr-school-1',
        actorName: 'أ. أحمد القحطاني',
        actorRole: 'SCHOOL_REP',
        timestamp: '2026-07-20T08:30:00Z',
        notes: 'تم تقديم طلب التقييم والتشخيص من قبل المدرسة بناءً على طلب ولي الأمر',
      },
      {
        id: 'h-2',
        requestId: 'req-101',
        fromStatus: 'SUBMITTED',
        toStatus: 'DOC_REVIEW',
        actorId: 'usr-reception-1',
        actorName: 'سارة عبد الله الشمري',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-20T09:00:00Z',
        notes: 'بدء مراجعة وتدقيق المرفقات والمستندات',
      },
      {
        id: 'h-3',
        requestId: 'req-101',
        fromStatus: 'DOC_REVIEW',
        toStatus: 'DOCS_COMPLETE',
        actorId: 'usr-reception-1',
        actorName: 'سارة عبد الله الشمري',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-20T10:30:00Z',
        notes: 'المستندات مكتملة ومطابقة لمتطلبات التسجيل',
      },
      {
        id: 'h-4',
        requestId: 'req-101',
        fromStatus: 'DOCS_COMPLETE',
        toStatus: 'PRIORITY_TRIAGE',
        actorId: 'usr-coord-1',
        actorName: 'د. فيصل بن خالد الدوسري',
        actorRole: 'CENTER_COORDINATOR',
        timestamp: '2026-07-21T08:00:00Z',
        notes: 'تصنيف الحالة بأولوية عالية بناء على التقرير النموذجي',
      },
      {
        id: 'h-5',
        requestId: 'req-101',
        fromStatus: 'PRIORITY_TRIAGE',
        toStatus: 'REFERRED_TO_CENTER',
        actorId: 'usr-coord-1',
        actorName: 'د. فيصل بن خالد الدوسري',
        actorRole: 'CENTER_COORDINATOR',
        timestamp: '2026-07-21T08:15:00Z',
        notes: 'إحالة الحالة لمركز الرياض الرئيسي للتدخل المبكر',
      },
      {
        id: 'h-6',
        requestId: 'req-101',
        fromStatus: 'REFERRED_TO_CENTER',
        toStatus: 'ACCEPTED_BY_CENTER',
        actorId: 'usr-supervisor-1',
        actorName: 'د. هدى التميمي',
        actorRole: 'SUPERVISOR',
        timestamp: '2026-07-21T09:00:00Z',
        notes: 'قبول الحالة وتخصيص الطاقة الاستيعابية للجلسات',
      },
      {
        id: 'h-7',
        requestId: 'req-101',
        fromStatus: 'ACCEPTED_BY_CENTER',
        toStatus: 'TEAM_ASSIGNED',
        actorId: 'usr-teamleader-1',
        actorName: 'د. عبد العزيز العتيبي',
        actorRole: 'TEAM_LEADER',
        timestamp: '2026-07-21T10:00:00Z',
        notes: 'تخصيص أخصائية نفسية وأخصائي نطق وتواصل',
      },
      {
        id: 'h-8',
        requestId: 'req-101',
        fromStatus: 'TEAM_ASSIGNED',
        toStatus: 'APPOINTMENT_SCHEDULED',
        actorId: 'usr-reception-1',
        actorName: 'سارة عبد الله الشمري',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-22T11:00:00Z',
        notes: 'حجز الموعد ليوم 2026-07-28 الساعة 09:00 صباحاً',
      },
      {
        id: 'h-9',
        requestId: 'req-101',
        fromStatus: 'APPOINTMENT_SCHEDULED',
        toStatus: 'APPOINTMENT_CONFIRMED',
        actorId: 'usr-parent-1',
        actorName: 'خالد بن محمد المطيري',
        actorRole: 'PARENT',
        timestamp: '2026-07-23T14:20:00Z',
        notes: 'تأكيد الموعد عبر بوابة ولي الأمر الإلكترونية',
      },
      {
        id: 'h-10',
        requestId: 'req-101',
        fromStatus: 'APPOINTMENT_CONFIRMED',
        toStatus: 'ATTENDED',
        actorId: 'usr-reception-1',
        actorName: 'سارة عبد الله الشمري',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-28T09:00:00Z',
        notes: 'حضور ولي الأمر والطالب لمقر المركز ودخول قاعة التقييم',
      },
      {
        id: 'h-11',
        requestId: 'req-101',
        fromStatus: 'ATTENDED',
        toStatus: 'UNDER_EVALUATION',
        actorId: 'usr-specialist-1',
        actorName: 'د. منيرة آل سعود',
        actorRole: 'DIAGNOSTIC_MEMBER',
        timestamp: '2026-07-28T09:30:00Z',
        notes: 'بدء الجلسة التشخيصية الأولى واستكمال تطبيق المقاييس المعيارية',
      },
    ],
    appointments: [
      {
        id: 'app-1',
        requestId: 'req-101',
        studentName: 'فهد خالد محمد المطيري',
        centerId: 'center-1',
        centerName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
        specialistId: 'usr-specialist-1',
        specialistName: 'د. منيرة آل سعود',
        specialization: 'التقييم النفسي والمعرفي',
        date: '2026-07-28',
        timeSlot: '09:00 ص - 10:30 ص',
        status: 'ATTENDED',
        notes: 'تمت جلسة التقييم المعرفي بنجاح',
      },
      {
        id: 'app-2',
        requestId: 'req-101',
        studentName: 'فهد خالد محمد المطيري',
        centerId: 'center-1',
        centerName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
        specialistId: 'usr-specialist-2',
        specialistName: 'أ. طارق المالكي',
        specialization: 'نطق وتواصل',
        date: '2026-08-02',
        timeSlot: '10:30 ص - 11:30 ص',
        status: 'SCHEDULED',
        notes: 'جلسة التقييم اللغوي والنطقي المقررة القادمة',
      },
    ],
    assessments: [
      {
        id: 'ass-1',
        requestId: 'req-101',
        specialistId: 'usr-specialist-1',
        specialistName: 'د. منيرة آل سعود',
        specialization: 'التقييم النفسي والمعرفي',
        assessmentDate: '2026-07-28',
        testUsed: 'مقياس وكسلر لذكاء الأطفال (WISC-V) + مقياس فينلاند للسلوك التكيفي',
        rawScore: 82,
        standardScore: 88,
        percentileRank: 21,
        clinicalSummary: 'يظهر الطالب قدرات معرفية في النطاق المتواضع المائل للمعطيات اللفظية المحدودة، مع درجات قصور واضحة في التفاعل الاجتماعي المباشر وفهم الإشارات التعبيرية غير اللفظية.',
        strengths: ['ذاكرة بصريو-مكانية جيدة جداً', 'دقة في التعرف على الأشكال والأنماط المعقدة'],
        needs: ['تنمية مهارات التواصل التبادلي', 'برنامج تعديل السلوك الاستجابي بالتواصل البديل'],
        dsmCode: 'F84.0 - Autism Spectrum Disorder (Level 1)',
      },
    ],
    recommendations: [
      {
        id: 'rec-1',
        requestId: 'req-101',
        category: 'CLASSROOM_ACCOMMODATION',
        title: 'توفير البيئة البصرية المجهزة داخل الفصل',
        description: 'استخدام الجدول البصري اليومي للأنشطة والمهام الدراسية وتقليل المثيرات المشتتة بالقرب من مقعد الطالب.',
        suggestedBy: 'د. منيرة آل سعود',
        isApprovedByTeam: true,
      },
      {
        id: 'rec-2',
        requestId: 'req-101',
        category: 'SPEECH_THERAPY',
        title: 'جلسات تخاطب فردية بمعدل 3 جلسات أسبوعياً',
        description: 'التركيز على مهارات اللغة الاستقبالية والتواصل غير اللفظي وتوسيع المفردات اللغوية.',
        suggestedBy: 'أ. طارق المالكي',
        isApprovedByTeam: true,
      },
      {
        id: 'rec-3',
        requestId: 'req-101',
        category: 'ASSISTIVE_TECH',
        title: 'استخدام أجهزة التواصل البديل والمعزز (PECS / AAC)',
        description: 'تطبيق التبادل بالصور للتعبيير عن الاحتياجات الأساسية ومنع النوبات عند الاحباط.',
        suggestedBy: 'مساعد الذكاء الاصطناعي (AI Draft)',
        isApprovedByTeam: false,
      },
    ],
    approvals: [
      {
        id: 'appr-1',
        requestId: 'req-101',
        approverRole: 'TEAM_LEADER',
        approverName: 'د. عبد العزيز العتيبي',
        status: 'PENDING',
      },
    ],
    diagnosisSummary: 'اشتباه اضطراب طيف التوحد (بدرجة بسيطة إلى متوسطة تحتاج دعم مبكر) مع تأخر لغوي نطق تواصل.',
  },
  {
    id: 'req-102',
    requestNumber: 'SHK-2026-0032',
    studentId: 'std-2',
    student: INITIAL_STUDENTS[1],
    schoolId: 'school-1',
    schoolName: 'مدرسة الأمل النموذجية الابتدائية',
    referredCenterId: 'center-1',
    referredCenterName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
    primaryCategory: 'LEARNING_DISABILITY',
    primaryCategoryArabic: 'صعوبات تعلم محددة (القراءة والكتابة)',
    priority: 'NORMAL',
    status: 'DOCS_INCOMPLETE',
    statusArabic: 'مستندات ناقصة',
    assignedTeamLeaderId: 'usr-teamleader-1',
    assignedTeamLeaderName: 'د. عبد العزيز العتيبي',
    assignedSpecialists: [],
    receptionistId: 'usr-reception-1',
    receptionistName: 'سارة عبد الله الشمري',
    createdAt: '2026-07-25T10:00:00Z',
    updatedAt: '2026-07-27T09:30:00Z',
    slaDaysTotal: 10,
    slaDaysRemaining: 8,
    isSlaPaused: true,
    slaBreached: false,
    documents: [
      {
        id: 'doc-10',
        requestId: 'req-102',
        title: 'صورة الهوية الوطنية',
        category: 'NATIONAL_ID',
        fileUrl: '/docs/reema_id.pdf',
        fileName: 'reema_id.pdf',
        fileSize: '1.1 MB',
        uploadedBy: 'عبد الله السبيعي',
        uploadedAt: '2026-07-25T10:15:00Z',
        isVerified: true,
      },
    ],
    statusHistory: [
      {
        id: 'h-20',
        requestId: 'req-102',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        actorId: 'usr-school-1',
        actorName: 'أ. أحمد القحطاني',
        actorRole: 'SCHOOL_REP',
        timestamp: '2026-07-25T10:00:00Z',
        notes: 'إحالة طالبة تعاني من تراجع ملحوظ بالتحصيل الدراسي',
      },
      {
        id: 'h-21',
        requestId: 'req-102',
        fromStatus: 'SUBMITTED',
        toStatus: 'DOC_REVIEW',
        actorId: 'usr-reception-1',
        actorName: 'سارة عبد الله الشمري',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-26T08:30:00Z',
        notes: 'مراجعة المرفقات المدرسية والطبية',
      },
      {
        id: 'h-22',
        requestId: 'req-102',
        fromStatus: 'DOC_REVIEW',
        toStatus: 'DOCS_INCOMPLETE',
        actorId: 'usr-reception-1',
        actorName: 'سارة عبد الله الشمري',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-27T09:30:00Z',
        notes: 'ينقص الملف: التقرير النموذجي السمعي والبصري وموافقة ولي الأمر الموقعة. تم إيقاف SLA وإرسال إشعار تذكير.',
      },
    ],
    appointments: [],
    assessments: [],
    recommendations: [],
    approvals: [],
  },
  {
    id: 'req-103',
    requestNumber: 'SHK-2026-0018',
    studentId: 'std-3',
    student: INITIAL_STUDENTS[2],
    schoolId: 'school-2',
    schoolName: 'مجمع المستقبل التعليمي',
    referredCenterId: 'center-1',
    referredCenterName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
    primaryCategory: 'ADHD',
    primaryCategoryArabic: 'اضطراب فرط الحركة وتشتت الانتباه',
    priority: 'EMERGENT',
    status: 'APPROVED',
    statusArabic: 'معتمــد رسمياً',
    assignedTeamLeaderId: 'usr-teamleader-1',
    assignedTeamLeaderName: 'د. عبد العزيز العتيبي',
    assignedSpecialists: ['د. منيرة آل سعود (نفسي)'],
    receptionistId: 'usr-reception-1',
    receptionistName: 'سارة عبد الله الشمري',
    createdAt: '2026-07-10T08:00:00Z',
    updatedAt: '2026-07-29T16:00:00Z',
    slaDaysTotal: 2,
    slaDaysRemaining: 0,
    isSlaPaused: false,
    slaBreached: false,
    qrCodeUrl: 'https://shakhesni.sa/verify/SHK-2026-0018',
    reportVerificationToken: 'VRF-9921-0018-SA',
    documents: [
      {
        id: 'doc-30',
        requestId: 'req-103',
        title: 'ملف الفحوصات الطبية الكاملة والهوية',
        category: 'MEDICAL_REPORT',
        fileUrl: '/docs/omar_complete.pdf',
        fileName: 'omar_complete.pdf',
        fileSize: '4.5 MB',
        uploadedBy: 'يوسف الدوسري',
        uploadedAt: '2026-07-10T08:30:00Z',
        isVerified: true,
      },
    ],
    statusHistory: [
      {
        id: 'h-30',
        requestId: 'req-103',
        fromStatus: 'ADMIN_REVIEW',
        toStatus: 'APPROVED',
        actorId: 'usr-supervisor-1',
        actorName: 'د. هدى التميمي',
        actorRole: 'SUPERVISOR',
        timestamp: '2026-07-29T16:00:00Z',
        notes: 'تمت المراجعة والاعتماد النهائي مع التوقيع الرقمي والختم المعتمد للمركز',
      },
    ],
    appointments: [
      {
        id: 'app-30',
        requestId: 'req-103',
        studentName: 'عمر بن يوسف الدوسري',
        centerId: 'center-1',
        centerName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
        specialistId: 'usr-specialist-1',
        specialistName: 'د. منيرة آل سعود',
        specialization: 'التقييم النفسي والمعرفي',
        date: '2026-07-18',
        timeSlot: '11:00 ص - 12:30 م',
        status: 'ATTENDED',
      },
    ],
    assessments: [
      {
        id: 'ass-30',
        requestId: 'req-103',
        specialistId: 'usr-specialist-1',
        specialistName: 'د. منيرة آل سعود',
        specialization: 'التقييم النفسي المعرفي',
        assessmentDate: '2026-07-18',
        testUsed: 'مقياس كونرز لتقييم اضطراب فرط الحركة وتشتت الانتباه (Conners-3)',
        rawScore: 78,
        standardScore: 115,
        percentileRank: 92,
        clinicalSummary: 'يظهر التقييم مؤشرات مرتفعة جداً في مقاييس اندفاعية وفرط الحركة وتشتت الانتباه في البيئة المدرسية والمنزلية.',
        strengths: ['ذكاء عام في الحد الطبيعي المرتفع', 'تفوق مهارات الابتكار وحل المشكلات البصرية'],
        needs: ['خطة تعديل سلوك مخصصة بالتعاون مع المرشد الطلابي', 'تجزئة المهام الدراسية لتنفيذها على فترات قصيرة'],
        dsmCode: 'F90.2 - ADHD Combined Presentation',
      },
    ],
    recommendations: [
      {
        id: 'rec-30',
        requestId: 'req-103',
        category: 'CLASSROOM_ACCOMMODATION',
        title: 'الجلوس في المقاعد الأمامية وتخصيص وقتاً إضافياً للاختبارات',
        description: 'إبعاد الطالب عن المنافذ المشتتة وإتاحة فترات راحة بينية 5 دقائق كل 20 دقيقة.',
        suggestedBy: 'د. منيرة آل سعود',
        isApprovedByTeam: true,
      },
    ],
    approvals: [
      {
        id: 'appr-30',
        requestId: 'req-103',
        approverRole: 'TEAM_LEADER',
        approverName: 'د. عبد العزيز العتيبي',
        status: 'APPROVED',
        signatureTimestamp: '2026-07-29T14:00:00Z',
        signatureHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        notes: 'موافقة رئيس الفريق الفني',
      },
      {
        id: 'appr-31',
        requestId: 'req-103',
        approverRole: 'SUPERVISOR',
        approverName: 'د. هدى التميمي',
        status: 'APPROVED',
        signatureTimestamp: '2026-07-29T16:00:00Z',
        signatureHash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
        notes: 'تم الاعتماد النهائي والختم المعتمد للمركز',
      },
    ],
    diagnosisSummary: 'اضطراب فرط الحركة وتشتت الانتباه (النمط المشترك - ADHD Combined Type).',
    finalDiagnosisCode: 'F90.2 - ADHD',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    requestId: 'req-101',
    actorName: 'سارة عبد الله الشمري',
    actorRole: 'RECEPTIONIST',
    action: 'مراجعة وتدقيق مستندات الطالب (فهد المطيري)',
    ipAddress: '192.168.1.45',
    timestamp: '2026-07-20T09:00:00Z',
    details: 'تم التحقق من مطابقة الهوية الوطنية والتقارير الطبية الأولية بنجاح.',
  },
  {
    id: 'log-2',
    requestId: 'req-101',
    actorName: 'د. فيصل بن خالد الدوسري',
    actorRole: 'CENTER_COORDINATOR',
    action: 'إحالة الطلب إلى المركز وتحديث الأولوية إلى (عالية)',
    ipAddress: '192.168.1.88',
    timestamp: '2026-07-21T08:15:00Z',
    details: 'تم تعيين درجة الأولوية بناء على نتائج التقييم النموذجي الطبي.',
  },
  {
    id: 'log-3',
    requestId: 'req-103',
    actorName: 'د. هدى التميمي',
    actorRole: 'SUPERVISOR',
    action: 'توقيع واعتماد التقرير التشخيصي النهائي رقم (SHK-2026-0018)',
    ipAddress: '192.168.1.12',
    timestamp: '2026-07-29T16:00:00Z',
    details: 'تم توليد التوقيع الرقمي والختم الرسمي وتوليد رمز QR التفاعلي للتحقق.',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-reception-1',
    role: 'RECEPTIONIST',
    title: 'طلب جديد بانتظار مراجعة المستندات',
    message: 'تم إحالة طلب تشخيص جديد للطالب (فهد المطيري) من مدرسة الأمل.',
    type: 'ACTION_REQUIRED',
    timestamp: '2026-07-20T08:35:00Z',
    isRead: false,
    linkUrl: '/requests/req-101',
  },
  {
    id: 'notif-2',
    userId: 'usr-parent-1',
    role: 'PARENT',
    title: 'تأكيد موعد جلسة التشخيص',
    message: 'نرجو تأكيد موعد جلسة التشخيص المقررة يوم الثلاثاء 2026-07-28.',
    type: 'INFO',
    timestamp: '2026-07-22T11:05:00Z',
    isRead: true,
    linkUrl: '/requests/req-101',
  },
  {
    id: 'notif-3',
    userId: 'usr-parent-2',
    role: 'PARENT',
    title: 'مستندات ناقصة مطلوبة للطلب',
    message: 'يرجى إرفاق التقرير الطبي السمعي المعتمد لاستكمال دراسة طلب الطالبة (ريما السبيعي).',
    type: 'DOCUMENT_MISSING',
    timestamp: '2026-07-27T09:35:00Z',
    isRead: false,
    linkUrl: '/requests/req-102',
  },
];
