import {
  User,
  School,
  DiagnosticCenter,
  Student,
  DiagnosisRequest,
  AuditLogEntry,
  Notification,
} from '@/types/database';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'أ. هيثم',
    email: 'haitham@shakhesni.sa',
    phone: '0501122334',
    role: 'SYSTEM_ADMIN',
    roleArabic: 'مدير النظام',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Haitham&backgroundColor=b6e3f4',
  },
  {
    id: 'usr-reception-1',
    name: 'أ. ماريا',
    email: 'maria@shakhesni.sa',
    phone: '0502233445',
    role: 'RECEPTIONIST',
    roleArabic: 'موظفة الاستقبال',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Maria&backgroundColor=ffd5dc',
    centerId: 'center-1',
  },
  {
    id: 'usr-coord-1',
    name: 'أ. محمد',
    email: 'mohammed@shakhesni.sa',
    phone: '0503344556',
    role: 'CENTER_COORDINATOR',
    roleArabic: 'منسق مركز التشخيص',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Mohammed&backgroundColor=c0aede',
    centerId: 'center-1',
  },
  {
    id: 'usr-specialist-1',
    name: 'أ. سارة',
    email: 'sara@shakhesni.sa',
    phone: '0504455667',
    role: 'DIAGNOSTIC_MEMBER',
    roleArabic: 'أخصائية التقييم النفسي والمعرفي',
    specialization: 'التقييم النفسي والمعرفي WISC-V',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Sara&backgroundColor=ffdfbf',
    centerId: 'center-1',
  },
  {
    id: 'usr-teamleader-1',
    name: 'د. عبد الله',
    email: 'abdullah@shakhesni.sa',
    phone: '0505566778',
    role: 'TEAM_LEADER',
    roleArabic: 'رئيس الفريق التشخيصي',
    specialization: 'استشاري تشخيص اضطرابات النمو والتوحد',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Abdullah&backgroundColor=d1d4f9',
    centerId: 'center-1',
  },
  {
    id: 'usr-supervisor-1',
    name: 'د. عبد الله',
    email: 'abdullah.sup@shakhesni.sa',
    phone: '0506677889',
    role: 'SUPERVISOR',
    roleArabic: 'المشرف العام والمدير',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=AbdullahSup&backgroundColor=d1d4f9',
    centerId: 'center-1',
  },
  {
    id: 'usr-school-1',
    name: 'أ. محمد',
    email: 'mohammed.school@shakhesni.sa',
    phone: '0507788990',
    role: 'SCHOOL_REP',
    roleArabic: 'ممثل المدرسة (المرشد الطلابي)',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=SchoolRep&backgroundColor=c0aede',
    schoolId: 'school-1',
  },
  {
    id: 'usr-parent-1',
    name: 'أحمد خالد',
    email: 'ahmed.khalid@gmail.com',
    phone: '0551234567',
    role: 'PARENT',
    roleArabic: 'ولي أمر الطالب (خالد)',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Ahmed&backgroundColor=ffd5dc',
  },
];

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'school-1',
    code: 'SCH-RIY-001',
    name: 'مدرسة الرواد الابتدائية للبنين',
    city: 'الرياض',
    district: 'حي الصحافة',
    educationalStage: 'الابتدائية',
    principalName: 'أ. هيثم',
    counselorName: 'أ. محمد',
    counselorPhone: '0507788990',
    activeRequestsCount: 3,
  },
  {
    id: 'school-2',
    code: 'SCH-RIY-002',
    name: 'مجمع المستقبل التعليمي',
    city: 'الرياض',
    district: 'حي الملقا',
    educationalStage: 'المتوسطة',
    principalName: 'د. عبد الله',
    counselorName: 'أ. محمد',
    counselorPhone: '0507788990',
    activeRequestsCount: 2,
  },
];

export const INITIAL_CENTERS: DiagnosticCenter[] = [
  {
    id: 'center-1',
    code: 'CTR-RIY-CENTRAL',
    name: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
    city: 'الرياض',
    district: 'حي السليمانية',
    capacityPerDay: 15,
    activeTeamCount: 8,
    specializations: ['اضطراب طيف التوحد', 'صعوبات التعلم', 'الإعاقة الفكرية', 'اضطرابات النطق', 'فرط الحركة وتشتت الانتباه'],
    directorName: 'د. عبد الله',
    phone: '0114567890',
  },
  {
    id: 'center-2',
    code: 'CTR-JED-WEST',
    name: 'مركز التقييم الشامل لذوي الإعاقة - جدة',
    city: 'جدة',
    district: 'حي الشاطئ',
    capacityPerDay: 12,
    activeTeamCount: 6,
    specializations: ['اضطراب طيف التوحد', 'الإعاقات الحركية والبصرية', 'صعوبات التعلم'],
    directorName: 'د. عبد الله',
    phone: '0126543210',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    nationalId: '1092837465',
    fullName: 'خالد',
    gender: 'MALE',
    birthDate: '2018-04-12',
    ageYears: 8,
    grade: 'الصف الثاني الابتدائي',
    schoolId: 'school-1',
    schoolName: 'مدرسة الرواد الابتدائية للبنين',
    parentId: 'usr-parent-1',
    parentName: 'أحمد خالد',
    parentPhone: '0551234567',
    parentEmail: 'ahmed.khalid@gmail.com',
    medicalConditions: 'تأخر نمائي لغوي ملحوظ وصعوبة في التواصل الاجتماعي والتفاعل مع الأقران',
    notes: 'ملاحظ من قبل المعلم بعدم الاندماج ومواجهة نوبات تشتت عند تغير الروتين اليومي',
  },
  {
    id: 'std-2',
    nationalId: '1102938475',
    fullName: 'خالد',
    gender: 'MALE',
    birthDate: '2017-09-25',
    ageYears: 9,
    grade: 'الصف الثالث الابتدائي',
    schoolId: 'school-1',
    schoolName: 'مدرسة الرواد الابتدائية للبنين',
    parentId: 'usr-parent-1',
    parentName: 'أحمد خالد',
    parentPhone: '0551234567',
    parentEmail: 'ahmed.khalid@gmail.com',
    medicalConditions: 'صعوبة بالغة في قراءة الكلمات والفقرات والكتابة',
    notes: 'تحتاج لتقييم صعوبات تعلم محددة في القراءة والكتابة (Dyslexia)',
  },
];

export const INITIAL_REQUESTS: DiagnosisRequest[] = [
  {
    id: 'req-101',
    requestNumber: 'SHK-2026-0041',
    studentId: 'std-1',
    student: INITIAL_STUDENTS[0],
    schoolId: 'school-1',
    schoolName: 'مدرسة الرواد الابتدائية للبنين',
    referredCenterId: 'center-1',
    referredCenterName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
    primaryCategory: 'AUTISM',
    primaryCategoryArabic: 'اشتباه اضطراب طيف التوحد',
    priority: 'HIGH',
    status: 'UNDER_EVALUATION',
    statusArabic: 'تحت التقييم والتشخيص',
    assignedTeamLeaderId: 'usr-teamleader-1',
    assignedTeamLeaderName: 'د. عبد الله',
    assignedSpecialists: ['أ. سارة', 'د. عبد الله'],
    receptionistId: 'usr-reception-1',
    receptionistName: 'أ. ماريا',
    createdAt: '2026-07-20T08:30:00Z',
    updatedAt: '2026-07-30T11:15:00Z',
    slaDaysTotal: 5,
    slaDaysRemaining: 2,
    isSlaPaused: false,
    slaBreached: false,
    qrCodeUrl: 'https://shakhesni.sa/verify/SHK-2026-0041',
    reportVerificationToken: 'VRF-8849-0041-SA',
    documents: [
      {
        id: 'doc-1',
        requestId: 'req-101',
        title: 'صورة هوية الطالب وولي الأمر',
        category: 'NATIONAL_ID',
        fileUrl: '/docs/national_id.pdf',
        fileName: 'identity_khalid.pdf',
        fileSize: '1.2 MB',
        uploadedBy: 'أ. ماريا',
        uploadedAt: '2026-07-20T09:00:00Z',
        isVerified: true,
        aiAuditResult: {
          status: 'COMPLETE',
          summary: 'تم التحقق من مطابقة رقم الهوية والاسم مع السجل المدني للطلاب بنسبة 100%',
        },
      },
      {
        id: 'doc-2',
        requestId: 'req-101',
        title: 'التقرير الطبي الأولي لمركز الرعاية الصحية',
        category: 'MEDICAL_REPORT',
        fileUrl: '/docs/medical_report.pdf',
        fileName: 'pediatric_report.pdf',
        fileSize: '2.8 MB',
        uploadedBy: 'أحمد خالد (ولي الأمر)',
        uploadedAt: '2026-07-20T09:30:00Z',
        isVerified: true,
        aiAuditResult: {
          status: 'COMPLETE',
          summary: 'يتضمن التقرير فحوصات السمع والنظر الأساسية وتاريخ التطور النمائي للطفل',
        },
      },
      {
        id: 'doc-3',
        requestId: 'req-101',
        title: 'ملاحظات المرشد الطلابي وتقييم المدرسة',
        category: 'SCHOOL_REPORT',
        fileUrl: '/docs/school_report.pdf',
        fileName: 'school_assessment.pdf',
        fileSize: '950 KB',
        uploadedBy: 'أ. محمد',
        uploadedAt: '2026-07-20T10:00:00Z',
        isVerified: true,
      },
    ],
    statusHistory: [
      {
        id: 'h-1',
        requestId: 'req-101',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        actorId: 'usr-school-1',
        actorName: 'أ. محمد',
        actorRole: 'SCHOOL_REP',
        timestamp: '2026-07-20T08:30:00Z',
        notes: 'تم تقديم طلب التقييم والتشخيص من قبل المدرسة بناءً على طلب ولي الأمر',
      },
      {
        id: 'h-2',
        requestId: 'req-101',
        fromStatus: 'SUBMITTED',
        toStatus: 'DOC_REVIEW',
        actorId: 'usr-reception-1',
        actorName: 'أ. ماريا',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-20T09:00:00Z',
        notes: 'بدء مراجعة وتدقيق المرفقات والمستندات',
      },
      {
        id: 'h-3',
        requestId: 'req-101',
        fromStatus: 'DOC_REVIEW',
        toStatus: 'DOC_REVIEW',
        actorId: 'usr-reception-1',
        actorName: 'أ. ماريا',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-20T10:30:00Z',
        notes: 'المستندات مكتملة ومطابقة لمتطلبات التسجيل',
      },
      {
        id: 'h-4',
        requestId: 'req-101',
        fromStatus: 'DOC_REVIEW',
        toStatus: 'PRIORITY_TRIAGE',
        actorId: 'usr-coord-1',
        actorName: 'أ. محمد',
        actorRole: 'CENTER_COORDINATOR',
        timestamp: '2026-07-21T08:00:00Z',
        notes: 'تصنيف الحالة بأولوية عالية بناء على التقرير النموذجي',
      },
      {
        id: 'h-5',
        requestId: 'req-101',
        fromStatus: 'PRIORITY_TRIAGE',
        toStatus: 'APPOINTMENT_SCHEDULED',
        actorId: 'usr-reception-1',
        actorName: 'أ. ماريا',
        actorRole: 'RECEPTIONIST',
        timestamp: '2026-07-22T11:00:00Z',
        notes: 'حجز الموعد ليوم 2026-07-28 الساعة 09:00 صباحاً للأخصائية أ. سارة',
      },
      {
        id: 'h-6',
        requestId: 'req-101',
        fromStatus: 'APPOINTMENT_SCHEDULED',
        toStatus: 'UNDER_EVALUATION',
        actorId: 'usr-specialist-1',
        actorName: 'أ. سارة',
        actorRole: 'DIAGNOSTIC_MEMBER',
        timestamp: '2026-07-28T09:30:00Z',
        notes: 'بدء الجلسة التشخيصية الأولى واستكمال تطبيق المقاييس المعيارية',
      },
    ],
    appointments: [
      {
        id: 'app-1',
        requestId: 'req-101',
        studentName: 'خالد',
        specialistName: 'أ. سارة',
        specialization: 'التقييم النفسي والمعرفي',
        date: '2026-08-25',
        timeSlot: '09:00 ص - 10:30 ص',
        status: 'ATTENDED',
        notes: 'تمت جلسة التقييم المعرفي بنجاح',
      },
      {
        id: 'app-2',
        requestId: 'req-101',
        studentName: 'خالد',
        specialistName: 'أ. هيثم',
        specialization: 'نطق وتواصل',
        date: '2026-08-28',
        timeSlot: '10:30 ص - 11:30 ص',
        status: 'SCHEDULED',
        notes: 'جلسة التقييم اللغوي والنطقي المقررة القادمة',
      },
    ],
    assessments: [
      {
        id: 'ass-1',
        requestId: 'req-101',
        specialistId: 'usr-specialist-1',
        specialistName: 'أ. سارة',
        specialization: 'التقييم النفسي والمعرفي',
        assessmentDate: '2026-07-28',
        testUsed: 'مقياس وكسلر لذكاء الأطفال (WISC-V) + مقياس فينلاند للسلوك التكيفي',
        rawScore: 82,
        standardScore: 88,
        percentileRank: 21,
        clinicalSummary: 'يظهر الطالب قدرات معرفية في النطاق المتواضع المائل للمعطيات اللفظية المحدودة، مع درجات قصور واضحة في التفاعل الاجتماعي المباشر وفهم الإشارات التعبيرية غير اللفظية.',
        strengths: ['ذاكرة بصريو-مكانية جيدة جداً', 'دقة في التعرف على الأشكال والأنماط المعقدة'],
        needs: ['تنمية مهارات التواصل التبادلي', 'برنامج تعديل السلوك الاستجابي بالتواصل البديل'],
        dsmCode: 'F84.0 - Autism Spectrum Disorder (Level 1)',
      },
    ],
    recommendations: [
      {
        id: 'rec-1',
        requestId: 'req-101',
        category: 'CLASSROOM_ACCOMMODATION',
        title: 'توفير البيئة البصرية المجهزة داخل الفصل',
        description: 'استخدام الجدول البصري اليومي للأنشطة والمهام الدراسية وتقليل المثيرات المشتتة بالقرب من مقعد الطالب.',
        suggestedBy: 'أ. سارة',
        isApprovedByTeam: true,
      },
      {
        id: 'rec-2',
        requestId: 'req-101',
        category: 'SPEECH_THERAPY',
        title: 'جلسات تخاطب فردية بمعدل 3 جلسات أسبوعياً',
        description: 'التركيز على مهارات اللغة الاستقبالية والتواصل غير اللفظي وتوسيع المفردات اللغوية.',
        suggestedBy: 'أ. هيثم',
        isApprovedByTeam: true,
      },
    ],
    approvals: [
      {
        id: 'appr-1',
        requestId: 'req-101',
        approverRole: 'TEAM_LEADER',
        approverName: 'د. عبد الله',
        status: 'PENDING',
      },
    ],
    diagnosisSummary: 'اشتباه اضطراب طيف التوحد (بدرجة بسيطة تحتاج دعم مبكر) مع تأخر لغوي في التواصل.',
  },
  {
    id: 'req-102',
    requestNumber: 'SHK-2026-0018',
    studentId: 'std-2',
    student: INITIAL_STUDENTS[1],
    schoolId: 'school-1',
    schoolName: 'مدرسة الرواد الابتدائية للبنين',
    referredCenterId: 'center-1',
    referredCenterName: 'مركز التشخيص والتدخل المبكر الموحد - الرياض',
    primaryCategory: 'LEARNING_DISABILITY',
    primaryCategoryArabic: 'صعوبات التعلم الأكاديمية (Dyslexia)',
    priority: 'NORMAL',
    status: 'APPROVED',
    statusArabic: 'معتمــد رسمياً',
    assignedTeamLeaderId: 'usr-teamleader-1',
    assignedTeamLeaderName: 'د. عبد الله',
    assignedSpecialists: ['أ. سارة'],
    receptionistId: 'usr-reception-1',
    receptionistName: 'أ. ماريا',
    createdAt: '2026-07-10T08:00:00Z',
    updatedAt: '2026-07-29T16:00:00Z',
    slaDaysTotal: 10,
    slaDaysRemaining: 8,
    isSlaPaused: false,
    slaBreached: false,
    qrCodeUrl: 'https://shakhesni.sa/verify/SHK-2026-0018',
    reportVerificationToken: 'VRF-9921-0018-SA',
    documents: [
      {
        id: 'doc-30',
        requestId: 'req-102',
        title: 'ملف الفحوصات الطبية الكاملة والهوية',
        category: 'MEDICAL_REPORT',
        fileUrl: '/docs/khalid_complete.pdf',
        fileName: 'khalid_complete.pdf',
        fileSize: '4.5 MB',
        uploadedBy: 'أحمد خالد',
        uploadedAt: '2026-07-10T08:30:00Z',
        isVerified: true,
      },
    ],
    statusHistory: [
      {
        id: 'h-30',
        requestId: 'req-102',
        fromStatus: 'TEAM_LEADER_REVIEW',
        toStatus: 'APPROVED',
        actorId: 'usr-supervisor-1',
        actorName: 'د. عبد الله',
        actorRole: 'SUPERVISOR',
        timestamp: '2026-07-29T16:00:00Z',
        notes: 'تمت المراجعة والاعتماد النهائي مع التوقيع الرقمي والختم المعتمد للمركز',
      },
    ],
    appointments: [
      {
        id: 'app-30',
        requestId: 'req-102',
        studentName: 'خالد',
        specialistName: 'أ. سارة',
        specialization: 'التقييم النفسي والمعرفي',
        date: '2026-07-18',
        timeSlot: '11:00 ص - 12:30 م',
        status: 'ATTENDED',
      },
    ],
    assessments: [
      {
        id: 'ass-30',
        requestId: 'req-102',
        specialistName: 'أ. سارة',
        specialization: 'التقييم النفسي المعرفي',
        assessmentDate: '2026-07-18',
        testUsed: 'بطارية تقييم صعوبات التعلم الأكاديمية (المايكل بست)',
        rawScore: 78,
        standardScore: 92,
        percentileRank: 30,
        clinicalSummary: 'وجود فجوة ملحوظة في مهارات القراءة والاستيعاب مع مستوى ذكاء عام طبيعي ومتفوق.',
        strengths: ['ذكاء عام في الحد الطبيعي المرتفع', 'تفوق مهارات الابتكار وحل المشكلات البصرية'],
        needs: ['خطة تعديل سلوك مخصصة بالتعاون مع المرشد الطلابي', 'تجزئة المهام الدراسية لتنفيذها على فترات قصيرة'],
        dsmCode: 'F81.0 - Specific Learning Disorder with reading impairment',
      },
    ],
    recommendations: [
      {
        id: 'rec-30',
        requestId: 'req-102',
        category: 'CLASSROOM_ACCOMMODATION',
        title: 'الجلوس في المقاعد الأمامية وتخصيص وقتاً إضافياً للاختبارات',
        description: 'إبعاد الطالب عن المنافذ المشتتة وإتاحة فترات راحة بينية 5 دقائق كل 20 دقيقة.',
        suggestedBy: 'أ. سارة',
        isApprovedByTeam: true,
      },
    ],
    approvals: [
      {
        id: 'appr-30',
        requestId: 'req-102',
        approverRole: 'TEAM_LEADER',
        approverName: 'د. عبد الله',
        status: 'APPROVED',
        signatureTimestamp: '2026-07-29T14:00:00Z',
        signatureHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        notes: 'موافقة رئيس الفريق الفني',
      },
      {
        id: 'appr-31',
        requestId: 'req-102',
        approverRole: 'SUPERVISOR',
        approverName: 'د. عبد الله',
        status: 'APPROVED',
        signatureTimestamp: '2026-07-29T16:00:00Z',
        signatureHash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
        notes: 'تم الاعتماد النهائي والختم المعتمد للمركز',
      },
    ],
    diagnosisSummary: 'صعوبات تعلم محددة في القراءة والكتابة (Dyslexia).',
    finalDiagnosisCode: 'F81.0',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    requestId: 'req-101',
    actorName: 'أ. ماريا',
    actorRole: 'RECEPTIONIST',
    action: 'مراجعة وتدقيق مستندات الطالب (خالد)',
    ipAddress: '192.168.1.45',
    timestamp: '2026-07-20T09:00:00Z',
    details: 'تم التحقق من مطابقة الهوية الوطنية والتقارير الطبية الأولية بنجاح.',
  },
  {
    id: 'log-2',
    requestId: 'req-101',
    actorName: 'أ. محمد',
    actorRole: 'CENTER_COORDINATOR',
    action: 'إحالة الطلب إلى المركز وتحديث الأولوية إلى (عالية)',
    ipAddress: '192.168.1.88',
    timestamp: '2026-07-21T08:15:00Z',
    details: 'تم تعيين درجة الأولوية بناء على نتائج التقييم النموذجي الطبي.',
  },
  {
    id: 'log-3',
    requestId: 'req-102',
    actorName: 'د. عبد الله',
    actorRole: 'SUPERVISOR',
    action: 'توقيع واعتماد التقرير التشخيصي النهائي رقم (SHK-2026-0018)',
    ipAddress: '192.168.1.12',
    timestamp: '2026-07-29T16:00:00Z',
    details: 'تم توليد التوقيع الرقمي والختم الرسمي وتوليد رمز QR التفاعلي للتحقق.',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-reception-1',
    role: 'RECEPTIONIST',
    title: 'طلب جديد بانتظار مراجعة المستندات',
    message: 'تم إحالة طلب تشخيص جديد للطالب (خالد) من مدرسة الرواد.',
    type: 'ACTION_REQUIRED',
    timestamp: '2026-07-20T08:35:00Z',
    isRead: false,
    linkUrl: '/requests/req-101',
  },
  {
    id: 'notif-2',
    userId: 'usr-parent-1',
    role: 'PARENT',
    title: 'تأكيد موعد جلسة التشخيص',
    message: 'نرجو تأكيد موعد جلسة التشخيص المقررة للطالب (خالد).',
    type: 'INFO',
    timestamp: '2026-07-22T11:05:00Z',
    isRead: true,
    linkUrl: '/requests/req-101',
  },
];
